version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraudlens_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - RANDOM_SEED=42
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=True
    # command: python -m uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
